### ISSUE TITLE
Unexpected error importing lucide-icons/group.py

### ISSUE THREAD

**Issue by hiddevanbrussel** [karlis-vagalis/hass-lucide-icons#1]
Logger: homeassistant.helpers.integration_platform
Source: helpers/integration_platform.py:50
First occurred: 11:03:30 (7 occurrences)
Last logged: 11:09:12

Unexpected error importing lucide-icons/group.py
Unexpected error importing lucide-icons/logbook.py
Unexpected error importing lucide-icons/media_source.py
Unexpected error importing lucide-icons/system_health.py
Unexpected error importing lucide-icons/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 834, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 851, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.lucideicons.diagnostics'

**Comment by hiddevanbrussel** [comment]
Problem solved. I've change the folder name **lucideicons** to **lucide-icons**
